### ISSUE TITLE
✨ Indent selected lines

### ISSUE THREAD

**Issue by MattKindzerske** [CodeEditApp/CodeEditSourceEditor#220]
### Description

When multiple lines are selected, the <kbd>tab</kbd> key should increase the indent of each line, instead of replacing the selected text with a tab. 

When text is selected...
- <kbd>tab</kbd> should increase indention level 
- <kbd>⇧</kbd> <kbd>tab</kbd> should decrease indentation level 
- <kbd>⌘</kbd> <kbd>]</kbd> should increase indention level 
- <kbd>⌘</kbd> <kbd>[</kbd> should decrease indentation level 

### Screenshots

<img width="1038" alt="image" src="https://github.com/user-attachments/assets/d7b30210-bc3e-4e92-9490-9d79c33d766c">

https://github.com/CodeEditApp/CodeEdit/assets/87990592/463a16ed-0da7-4bda-bb0b-b85eda423230

**Comment by austincondiff** [comment]
@thecoolwinter is this possible with the new text view?

**Comment by thecoolwinter** [comment]
> @thecoolwinter is this possible with the new text view?
> 
> Along with tab, `⌘]` and `⌘[` should increase and decrease respectively as well.

Yes it is, we'll just need to add some functionality to our tab replacement code. I'll work on getting this implemented next.

**Comment by ladvoc** [comment]
If you haven’t had a chance to work on this yet, I’m happy to step in. Let me know if that works for you.

**Comment by austincondiff** [comment]
@ladvoc I don't think anyone has started on this, I'd say go for it! Would you like me to assign this to you?

**Comment by ladvoc** [comment]
> @ladvoc I don't think anyone has started on this, I'd say go for it! Would you like me to assign this to you?

Yes, please do.

**Comment by austincondiff** [comment]
@ladvoc assigned to you. It may make sense to also knock out #259 in the same PR. I’ll let you decide if that makes sense once you dig into it.

**Comment by activcoding** [comment]
Hey @ladvoc, thanks a lot for taking the time to look into this issue! It seems there hasn't been much progress on it, so I’ve started working on it myself and it's already halfway done. I'll go ahead and assign it to myself and remove you.
