### ISSUE TITLE
✨ Changes to SwiftTreeSitter

### ISSUE THREAD

**Issue by mattmassicotte** [CodeEditApp/CodeEditSourceEditor#224]
### Description

I just wanted to let you know about some changes I've (finally!) getting close to finishing. Some API changes have been made to SwiftTreeSitter to improve compatibility with concurrency also fully support query predicate resolution (like locals). Sendable conformance, as is typical, was challenging. In particular, I had to introduce a new `MutableTree` type. Adopting all this should be relatively easy, but I wanted to give you a heads-up.

There is also some significant new features available in the `SwiftTreeSitterLayer` sub-library, though I suspect that won't be relevant since you've already got your own solution there.

There is currently no release with this changes, but one is coming soon. You can check out main now, if you want to get an idea.I will make myself available for any help you might need, so just let me know!

**Comment by thecoolwinter** [comment]
Thank you for the heads up here and in Discord! I've merged the changes and updated our implementation with #225, thanks for all the work you do on that package!
