### ISSUE TITLE
✨ Cocoapods

### ISSUE THREAD

**Issue by jdmg94** [CodeEditApp/CodeEditSourceEditor#226]
### Description

Are there any plans to make this package available through cocoapods?

**Comment by 0xWDG** [comment]
AFAIK there are no plans for Cocoapods.
The package is already available trough SPM (Swift Package Manager).

**Comment by jdmg94** [comment]
Thanks for the quick reply, I wasn't able to find the project on swift package index. I'm trying to use this for a react-native module and I'm not too familiar with the swift package manager ecosystem

**Comment by thecoolwinter** [comment]
I've opened an issue adding our packages with the package index, but you can still use the package without it being indexed. Just use the URL. I'm not quite sure how that will work with `react-native`, but we don't have any plans for supporting CocoaPods or any other package manager.
