### ISSUE TITLE
🐞 Some theme colors only apply after changing theme

### ISSUE THREAD

**Issue by austincondiff** [CodeEditApp/CodeEditSourceEditor#227]
### Description

Some colors from the selected theme are not applied to the editor until changing your theme.

### To Reproduce

1. Open editor
2. Notice current line highlight color is wrong
3. Open theme settings
4. Change theme to something else, then back to original theme
5. Notice the current line highlight color is now correct

### Expected Behavior

The current line color should use the color specified in the theme.

### Screenshots

https://github.com/CodeEditApp/CodeEditSourceEditor/assets/806104/6f03da87-7547-4fdb-b308-bedad9f8e860

**Comment by thecoolwinter** [comment]
@austincondiff have you noticed any other theme colors not being applied initially?
