### ISSUE TITLE
✨ Autocomplete angle bracketed components the same way braces are autocompleted

### ISSUE THREAD

**Issue by knotbin** [CodeEditApp/CodeEditSourceEditor#244]
### Description

When a user uses angle brackets with a component, for instance typing `<div>`, and then presses enter, the system autocompletes that component, adding `</div>` on the line below the new current line and indents the new current line.

### Screenshots

<img width="113" alt="Screenshot 2024-04-27 at 2 10 06 PM" src="https://github.com/CodeEditApp/CodeEditSourceEditor/assets/118622417/8b04c502-6622-40e9-b39b-35ddc27577aa">

**Comment by austincondiff** [comment]
This should probably only apply to html, xml, and jsx.
It should work like this…
1. User types `<` - no autocomplete occurs
2. User types tag name, `<div` - no autocomplete occurs
3. User types `>`, `<div>` - closing tag is autocomplete and is inserted directly after the opening tag. Cursor is placed in between tags. Eg. `<div>|</div>`
4. If user presses return, closing tag is moved to a new line, then cursor is placed on a new empty line and indented in between the other two lines. Eg…
```html
<div>
    |
</div>
```

**Comment by knotbin** [comment]
In addition to JSX and TSX, it should also apply to regular JS and TS files as JSX and TSX can be written inside regular JS and TS files.

**Comment by austincondiff** [comment]
@knotbin absolutely, good point! Would you be willing to take this one on?

**Comment by knotbin** [comment]
Sure @austincondiff!

**Comment by austincondiff** [comment]
You rock! One additional consideration, keep in mind that tags can be self closing, i.e. `<div />`, so we should not autocomplete when this is the case.
