### ISSUE TITLE
🐞 If you hold shift and click, you cannot select a range

### ISSUE THREAD

**Issue by RonghuaHe** [CodeEditApp/CodeEditSourceEditor#254]
### Description

If you hold shift and click, you cannot select a range

### To Reproduce

1.  If you hold shift and click, 
2. you cannot select a range
<img width="439" alt="001" src="https://github.com/CodeEditApp/CodeEditSourceEditor/assets/34976742/4ea82b7f-bd20-4a17-92a6-ab99143c6195">

### Expected Behavior

If you hold shift and click, you can select a range, Selection is just as powerful as NSTextView

### Version Information

CodeEditSourceEditor: [e.g. 0.x.y]
macOS: [e.g. 13.2.1]
Xcode: [e.g. 14.2]

**Comment by thecoolwinter** [comment]
Fixed with recent changes to CodeEditTextView.
